version: "3.8"

services:
  website1:
    image: website:latest
    container_name: website1
    ports:
      - "80:80"

  website2:
    image: website2:1.0
    container_name: website2
    ports:
      - "8081:80"
